# Generated by Django 4.2.6 on 2024-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arya',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
