# Generated by Django 4.2.6 on 2024-04-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arya',
        ),
    ]
