# Generated by Django 4.2.6 on 2024-04-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_arya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('thumbnail', models.CharField(max_length=1000)),
                ('other_pics', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=1000)),
                ('bio', models.TextField(max_length=150)),
                ('is_publisher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='Category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.categories'),
        ),
        migrations.AddField(
            model_name='articles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
    ]
