# Generated by Django 4.2.6 on 2024-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='other_pics',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
