# Generated by Django 4.2.6 on 2024-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_user_id_articles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likescount',
            field=models.IntegerField(default=0),
        ),
    ]
