# Generated by Django 4.2.6 on 2024-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_articles_dislikes_articles_likes_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.CharField(default='/static/images/profile_pics/defaultpfpsvg.png', max_length=200),
        ),
    ]
