# Generated by Django 4.2.6 on 2024-05-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_articles_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='dislikescount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('dislike_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Dislikes',
            },
        ),
    ]
